using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SchoolNames : MonoBehaviour
{
    public static SchoolNames Instance;

    private void Awake()
    {
        if (Instance == null)
        {
            Instance = this;
        }
        else if (Instance != null)
        {
            Destroy(this.gameObject);
        }
    }

    public void SchoolNamesFromAnkara()
    {
        SearchableDropDown.Instance.avlOptions.Add("100 Yýl Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("12 Eylül Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("15 Temmuz Demokrasi Þehitleri Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("19 Mayýs Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("29 Ekim Cumhuriyet Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("75. Yýl Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Abdi Ýpekçi Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Abdullah Tokur Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Abdurrahim Karakoç Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Abidinpaþa Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Açýkalýn Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Adalet Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Adnan Menderes Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Afþar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Afþin Bey Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Aða Ceylan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ahýboz Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ahi Evran Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ahiler Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ahmet Andiçen Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ahmet Barýndýrýr Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ahmet Haþim Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ahmet Hýzal Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ahmet Kabaklý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ahmet Müþerref Muhtaroðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ahmet Vefik Paþa Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Akgül Ulusoy Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Akýn Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Akkuzulu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Akþemsettin Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Akyurt Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Akyurt Yýldýrým Beyazýt Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Alahacýlý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ali Ersoy Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ali Kuþçu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ali Rýza Bey Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Alparslan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Alper Tunga Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Altýndað Piri Reis Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Altýnordu Layika Akbilek Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Altýnova Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ankara Ticaret Odasý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Arif Nihat Asya Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Arjantin Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Aselsan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Aþaðý Cavundur Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ataköy Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Atam Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Atatürk Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Atilla Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Avni Akyol Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Aydýnlýkevler Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ayþe Özbaðý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ayþe Tokur Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ayþegül Tuna Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ayyýldýz Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Azmi Ertuðrul Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Baðlýca Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Baðlum Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Bahçecik Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Bahçelievler Nebahat Keskin Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Bahri Hacýahmetoðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ballýkpýnar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Barbaros Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Barýþyolu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Barmek Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Barut Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Basri Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Batýkent Orhan Eren Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Bayýndýr Köyü Yunus Muftu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Bayrak Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Bedriye Halil Naci Mýhcýoðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Beylikköprü Þh.Yzb.Nazmi Elmas Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Beynam Emine Eriþen Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Beyobasý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Beypazarý Þehit Kemal Duman Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Beypazarý Þehit Onur Yaman Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Beytepe Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Bezirhane Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Bilge Kaðan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Bilkent Üniversitesi Müzik Ve Sahne Sanatlarý Fakültesi Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Biruni Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Boðaziçi Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Borsa Ýstanbul Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Borsa Ýstanbul Sincan Kayalýboðaz Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Bucuk Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Bumsuz Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Burak Reis Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Büðdüz Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Bünyamin Ayaþi Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Büyükboyalýk Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Büyükelçi Nazým Belger Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Büyükþehir Anfa Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Cahit Zarifoðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Catak Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Cebesoy Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Celayir Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Cemal Yüksel Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Cengizhan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Cumhuriyet Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Çaðatay Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Çaldað Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Çalýþkanlar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Çalören Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Çandýr Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Çanýllý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Çankaya Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Çayýrhan Cumhuriyet Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Çayýrhan Gazi Mete Okuducu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Çayýrlýoðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Çeltikçi Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Çigiltepe Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Çizmeci Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Çocuk Sevenler Derneði Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Çocuk Sevenler Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Çoðlu Vural Baylan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Çokören Satýlmýþ Yýlmaz Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Çubuk Süleyman Þah Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Danýþment Çiçekli Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Dede Korkut Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Dedeman Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Demirlibahçe Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Demirözü Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Doðan Çaðlar Bedensel Engelliler Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Dr.Ahmet Kazým Mýhçýoðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Dr.Reþit Galip Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Dsi Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Dumlupýnar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ege Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Elecik Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Emine Rasim Özkaya Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Emine Taþkent Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Emirler Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Emirler Kesikkavak Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Enver Bektaþ Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Erdoðan Þahinoðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ergazi Þehit Adil Yurtoðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ergenekon Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Eryaman Þehit Rýfat Çelik Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Eryaman Türkkent Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Evren Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Faik Erbaðý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Faik Hýzýroðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Faruk Kefelioðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Faruk Verimer Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Fatih Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Fatih Sultan Mehmet Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Fatin Rüþtü Zorlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Fatma Tarman Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Fevzi Özbey Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Fevziatlýoðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Fikri Ýnal Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Gazeteci Hasan Tahsin Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Gazi Ahmet Muhtar Paþa Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Gazi Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Gazi Osman Paþa Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Gaziosmanpaþa Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Gazipaþa Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Gençali Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Gökçe Karataþ Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Gökçehöyük Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Gökçeyurt Yibitaþ Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Göktürk Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Gölbaþý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Gölbaþý Þehit Ömer Halisdemir Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Göreneller Görme Engelliler Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Güldarpý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Gülpýnar Þehit Fatih Korçam Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Gülten Kösemen Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Gültepe Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Gülveren Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Gümüþoluk Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Gümüþpala Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Gündüz Alp Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Güneyce Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Güvem Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Güzelhisar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Hacý Ayþe Ýlik Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Hacý Hasan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Hacý Mehmet Uçar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Hacý Mustafa Tarman Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Hacýlar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Hakan Akbýyýk Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Hakan Ülger Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Halide Ömer Uncuoðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Halil Naci Mýhçýoðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Halim Þaþmaz Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Halise Arslan Özel Eðitim Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Halit Fahri Ozansoy Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Hamdi Bulgurlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Hamdi Eriþ Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Hamdiye Unlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Hamdullah Suphi Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Harzemþahlar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Hasanoðlan Öðretmenler Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Hasayaz Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Hayme Hatun Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Hayri Eriþen Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Hikmet Uluðbay Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Hurin Yavuzalp Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Hürriyet Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Hüseyin Güllü Ceylan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ilýca Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ýbni Haldun Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ýbrahim Akoðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ýbrahim Bitik Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ýbrahim Gürbüz Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ýhsan Köksal Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ýhsan Sungu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ýlhan Gerim Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ýltekin Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ýmrendi Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ýncek T.E.K. Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ýnkýlap Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ýnönü Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ýsmail Erez Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ýsmet Kurtuluþ Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ýstiklal Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ýzzet Latif Aras Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kadri Suyabakan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kalaba Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Karacahasan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Karacaoðlan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Karacaören Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Karahamzalý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Karapýnar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Karapürçek Þehit Ferhat Muratoðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Karataþ Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kaþgarlý Mahmut Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Katip Çelebi Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kavak Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kavaklý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kayalar Þehit Necmi Bahadýr Denizcioðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kayaþ Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kazým Karabekir Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kazým Orbay Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Keçiören Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Keçiören Þehit Fatih Erdoðan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Keçiören Þehit Fýrat Bulut Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Keçiören Yunus Emre Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kemal Atatürk Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kemal Milaslý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kemal Yurtbilir Ýþitme Engelliler Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kent Koop Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kerpiç Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kesikköprü Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kýbrýskoyu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kýlýçali Paþa Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kýnýk Þehit Murat Yatarkalkmaz Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kýrbaþý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kýrkkonaklar Ýffet Güneþoðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kýymet Necip Tesal Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kýzýk Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kocatepe Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Koç Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Korgeneral Ömer Keçecigil Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Korkut Ata Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kozayagý Köyü Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Köþklüdere Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Köy Hizmetleri Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kurtuluþ Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kusunlar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kutluhan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kuzeykent Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Kürþad Bey Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Lalahan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Lalahan Serdar Tosun Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Layika Akbilek Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Mahir Baþer Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Mareþal Fevzi Çakmak Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Mecidiye Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Mehmet Akif Ersoy Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Mehmet Akif Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Mehmet Akif Ýnan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Mehmet Emin Yurdakul Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Mehmet Hikmet Ayberk Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Mehmet Memiþoðullarý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Mehmet Rýfat Börekçi Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Mehmet Yetkin Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Mehmetçik Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Melek Özen Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Melýksah Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Melikþah Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Memlik Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Merkez Atatürk Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Mesa Koru Sitesi Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Metehan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Mevlana Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Milli Egemenlik Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Millî Eðitim Vakfý Gökkuþaðý Özel Eðitim Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Milli Eðitim Vakfý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Milli Müdafaa Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Misket Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Mitat Enç Görme Engelliler Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Mithatpaþa Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Mohaç Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Muazzez Karaçay Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Mustafa Kemal Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Mustafa Üstündað Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Müjgan Karaçalý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Münevver Osmankaya Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Nasreddin Hoca Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Nasuhpaþa Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Naþide Halil Gelendost Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Nazife Hatun Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Nebahat Taþkýn Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Necip Fazýl Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Necmi Þahin Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Nedim Ýnal Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Nedred Arif Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Nenehatun Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Nihat Baþakar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Nuh Eskiyapan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Nurçin Sayan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Oðuz Kaðan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Oðuzlar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Oltan Þehit Olgun Gökmen Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Orhan Cemal Fersoy Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Orhangazi Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ortaköy Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Oruç Reis Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Osman Gazi Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Osman Hamdibey Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Osman Ünyazýcý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Osmansin Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ostim Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Öðretmen Abdullah Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Öðretmen Hüseyin Hüsnü Tekýþýk Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Önder Ata Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Özbirlik Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Özdemir Gürocak Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Özyurt Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Paþalý Necati Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Perýhan Erdogan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Peyami Safa Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Peyamitepe Þehit Mehmet Kocakaya Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Pir Sultan Abdal Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Piri Reis Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Polatlý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Polatlý Þehit Abdullah Erkmen Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Polatlý Þehitlik Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Polis Amca Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Poyraz Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Pursaklar Satý Öztürk Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Rauf Orbay Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Refet Bele Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Refika Aksoy Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Reþatbey Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ruhiye Hilmi Atlýoðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Rüstempaþa Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sabiha Þaþmaz Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Saimekadýn Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sakalar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sakarya Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Samime Talat Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sancaktepe Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sanlýkýsla Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Saracalar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sarar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Saray Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Satuk Buðra Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Selçuklu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sevgi Çiçeði Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sevim Aras Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Seyit Onbaþý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Seymenler Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Seyranbaðlarý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sýdýka Hatun Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sýdýka Kýnacý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sinanlý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sincan Akþemsettin Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sincan Borsa Ýstanbul Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sincan Ýl Genel Meclisi Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sincan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sirkeli Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sofular Musa Ünal Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sofuoðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sokullu Mehmet Paþa Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Solfasol Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sultan Alparslan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Susuz Þehit Tamer Kýlýç Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Sühendan Kürklü Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Süleyman Nazif Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Süleyman Uyar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þafaktepe Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þahin Sevin Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þahinbey Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þair Nedim Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Ahmet Çaðlar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Ahmet Gözütok Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Ahmet Kabukçu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Ahmet Yetiþ Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Albay Ýbrahim Karaoðlanoðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Alper Kaymakcý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Alper Kocaman Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Arif Yüksekkaya Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Arslan Kulaksýz Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Aytaç Usta Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Battal Ýlgün Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Bülent Albayrak Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Bülent Göçer Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Cihan Yýldýz Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Çetin Sarýkaya Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Emre Karagöz Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Emre Tunca Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Ender Alper Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Erdinç Aydýn Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Erhan Ar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Erkan Tümer Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Ersin Utlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Evren Ayyarkýn Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Faruk Erarslanoðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Ferhat Koç Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Filiz Koçak Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Furkan Doðan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Güner Altýnok Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Hakan Kabil Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Hakan Toydemir Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Harun Aydýn Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Harun Parlak Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Hilmi Özer Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Hüseyin Köksal Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Ýbrahim Çoban Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Ýsmail Benli Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Ýzzet Özkan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Komando Onbaþý Mükremin Baþaran Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Kubilay Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Kuddusi Demli Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Mahmut Özdemir Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Mahmut Uslu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Mahsudi Yýlmaz Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Mehmet Akif Sancar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Mehmet Ali Yapraklý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Mehmet Altanlar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Mehmet Bora Tayfur Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Mehmet Çetin Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Miraç Yýldýrým Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Muhammed Ýsmail Kaya Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Murat Bek Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Mustafa Duman Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Mustafa Erdal Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Mustafa Karasakal Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Mustafa Tanýþ Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Mustafa Yiðitalp Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Öðretmen Nesrin Ünügür Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Ömer Azak Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Ömer Boztepe Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit P Üst Muharrem Kaleli Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Savaþ Býyýklý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Selahattin Þiþman Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Serkan Çaðlayan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Süleyman Can Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Sümer Deniz Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Þener Gündem Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Tahir Çakmak Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Teðmen Ertuðrul Pilatin Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Tolga Akdaþ Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Tufan Kansuva Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Turgay Topsakaloðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Volkan Alýcý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Volkan Külekci Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Yaþar Çetinkaya Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Yaþar Yavaþ Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Yavuz Baþayar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þehit Yunus Emre Duran Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þenlik Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þereflikoçhisar Toki Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þeyhþamil Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þh.Py.Er Murat Eroðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þili Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Þinasi Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("T.E.K. Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Talia Yaþar Bakdur Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Talip Yener Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Tandoðan Þehit Celalettin Ýbiþ Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Tarým Ýþletmesi Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Taþça Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Taþtepe Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Taylan Araslý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Teðmen Kalmaz Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Telsizler Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Temelli Toki Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Tepecik Dostlar Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Tepeköy Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Tevfik Ünsal Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Týnaztepe Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Toki Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Toki Malazgirt Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Topaklý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Tsk Mehmetcik Vakfý Hafize Ýhsan Payaza Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Tuðrulbey Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Tuna Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Tuna Üçer Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Turhan Dökmeci Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Turhan Feyzioðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Tuzgölü Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Tuzluçayýr Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Türk Telekom Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Türkan Azmi Köksoy Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Türkan Yamantürk Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Türkerler Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Türkiye Noterler Birliði Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Türkiye Saðlýk Ýþçileri Sendikasý Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Türkkonut Emel Önal Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Türkkonut Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ufuktepe Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ulubatlý Hasan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Uluðbey Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ulviye Fenmen Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Uzunbey Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Üçevler Aytekin Keser Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ülker Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Vehbi Dinçerler Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Vildan Nurettin Demirer Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yahya Çavuþ Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yahyalar Durali Bezci Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yakupoðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yalçýn Eskiyapan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yavuz Selim Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yavuz Sultan Selim Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yeni Turan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yenice Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yenihayat Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yenikent Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yenikent Ýlksan Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yenimutlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yenipeçenek Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yeþilköy Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yýldýrým Beyazýt Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yýlmaz Balaban Ýþitme Engelliler Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yukarý Peçenek Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yunus Emre Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yurtbeyi Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Yücetepe Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Zafer Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Zehra Önder Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Zeki Tartaç Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Zekiye Güdüllüoðlu Ýlkokulu");
        SearchableDropDown.Instance.avlOptions.Add("Ziya Gökalp Ýlkokulu");
    }
}
